### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: \'java -jar /home/***/tools/apktool.jar\'\n'（已解决）

### ISSUE THREAD

**Issue by SX1ang** [user1342/DISintegrity#2]
运行如下命令报错：
```
python3 /home/***/tools/DISintegrity-main/DISintegrity.py -apk /home/***/test.apk --apktool /home/***/tools/apktool.jar -o /tmp/tmpifb15wyp
```
![image](https://github.com/user1342/DISintegrity/assets/58685598/48f4baae-fa78-461d-818b-7c1b1f56bce9)

按照如上的方法做如下修复：
![image](https://github.com/user1342/DISintegrity/assets/58685598/7eb0fa7f-4a5c-4046-b250-146c2f01f983)

**Comment by user1342** [comment]
Fixed in #3 by @Vanlir !
